default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default

test:
  <<: *default

production:
  primary: &primary_production
    <<: *default
    database: myapp_production  # 必要に応じてデータベース名を適宜変更
  cable:
    <<: *primary_production  # cableも同じデータベースを使用
  queue:  # queueもprimaryと同じデータベースを使用
    <<: *primary_production
  cache:
    <<: *primary_production  # cacheもprimaryと同じデータベースを使用
